---
title: "13 - Assignment Kelley Brundage"
author: "Kelley Brundage"
date: "7/30/2019"
output:
  html_document:
    df_print: paged
Github: https://github.com/klbrundage/LLO8200-Assignments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,warning=FALSE,results='hide',include=TRUE,messages=FALSE)

##We always start with a standard set of setup commands by loading the correct libraries. We will continue to work with our existing libraries and will add 'caret' in order to evaluate the perforance of a classifier.

##Load libraries in order to successfully run the code below - the suppressMessages coding will stop the install.packages information, etc.. from coming up in the Console and showing you what has run.

suppressMessages(library(caret)) #Misc functions for training and plotting classification and regression models.
suppressMessages(library(dplyr)) #able to select, filter, organize, and manipulate data stored within an R data frame
suppressMessages(library(evaluate)) #Parsing and Evaluation Tools that Provide More Details than the Default
suppressMessages(library(flexclust))
suppressMessages(library(forcats)) #Tools for Working with Categorical Variables (Factors)
suppressMessages(library(formatR)) #Provides a function tidy_source() to format R source code.
suppressMessages(library(ggplot2)) #A system for 'declaratively' creating graphics, based on "The Grammar of Graphics".
suppressMessages(library(haven)) #Import foreign statistical formats into R via the embedded 'ReadStat' C library
suppressMessages(library(htmlwidgets))
suppressMessages(library(leaflet))
suppressMessages(library(LICORS))
suppressMessages(library(knitr))#General-Purpose Package for Dynamic Report Generation in R 
  opts_chunk$set(comment = NA)
  def_hook <- knit_hooks$get("output")
  knit_hooks$set(output = function(x, options)
    {out <- def_hook(x, options)
    return(paste("\\begin{framed}\\begin{verbatim}", x, "\\end{verbatim}\\end{framed}",
                 collapse = "\n"))})

suppressMessages(library(lubridate)) #Functions to work with date-times and time-spans: fast and user friendly parsing of date-time data, extraction and updating of components of a date-time
suppressMessages(library(ModelMetrics)) #Collection of metrics for evaluating models written in C++ using 'Rcpp'.
suppressMessages(library(modelr)) #Functions for modelling that help you seamlessly integrate modelling into a pipeline of data manipulation and visualisation.
suppressMessages(library(pander))#provide a minimal and easy tool for rendering R objects
  panderOptions('table.style', "multiline")
  panderOptions('table.alignment.default',function(df)ifelse(sapply(as.data.frame(df),
                                                            is.numeric),'right','left'))

suppressMessages(library(plotly))
suppressMessages(library(readxl)) #reads in Excel Files
suppressMessages(library(rvest)) #scraping websites
suppressMessages(library(shiny))
suppressMessages(library(stats))
suppressMessages(library(tibble)) #Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better formatting than the traditional data frame.
suppressMessages(library(tidyverse)) #set of packages that work in harmony because they share common data representations and 'API' design
suppressMessages(library(tictoc))#his package provides the timing functions 'tic' and 'toc' that can be nested. One can record all timings while a complex script is running, and examine the values later.
suppressMessages(library(tigris))

##Define My PDF setup
#This code does not show in the final document but will assist with definining the margin cutoff point and wraps the text to the next line.

knitr::opts_chunk$set(fig.path = "Figs/", results='hide', tidy.opts=list(width.cutoff=60)) 
  my_pdf = function(file,width,height)
  {pdf(file, width=width, height=height,pointsize=12)}
  
##Load the necessary datafiles for the assignment:
load("pd.Rdata")
load("cs.RData")

```


# **Question 1:**  
Using the county dataset, create an interactive scatterplot of homeowner-ship by education levels.  

```{r Descriptive for Plotly}
pd <- pd%>%
  mutate(coll_grad_rank=rank(coll_grad_pc))
```


```{r College Grad Comparison, results="asis"}

gg <- ggplot(pd, aes(x=coll_grad_pc, y=homeown_rate, size=pop2010,
                     text=paste0(county,
                                "<br>",
                                "Percent College Grad: ",
                                round(coll_grad_pc, 1),
                                "<br>",
                                "Homeownership: ",
                                prettyNum(median_hh_inc, big.mark = ","))))+
  geom_point(alpha=.5,color="lightblue")+
  xlab("Percent College Graduates")+ylab("Homeownership")

ggplotly(gg)
```


```{r High School Grad Comparison, results="asis"}

gg <- ggplot(pd, aes(x=hs_grad_pc, y=homeown_rate, size=pop2010,
                     text=paste0(county,
                                 "<br>",
                                 "Percent High School Grad: ",
                                 round(coll_grad_pc, 1),
                                 "<br>",
                                 "Home Ownership: ",
                                 prettyNum(median_home_val, big.mark = ","))))+
  geom_point(alpha=.5,color="thistle")+
  xlab("Percent High School Graduates")+ylab("Home Ownership")

ggplotly(gg)

```

# **Question 2:**  
Again using the county dataset, follow the steps used in class to create an interactive map of homeownership by county in your home state.  

```{r Interactive Map, results="asis"}

data(fips_codes)
states_list <- c("FL")

fips_codes <- fips_codes%>%
  group_by(state)%>%
  summarize(fips_code=first(state_code))
fips_list <- fips_codes%>%
  filter(state%in%states_list)
fips_list <- fips_list$fips_code

names(cs) <- tolower(names(cs))

cs <- cs[cs$statefp%in%c(fips_list), ]

pd_sub <- pd%>%
  select(fips,homeown_rate,county)%>%
  filter(grepl(states_list,county))

cs <- geo_join(cs,pd_sub,"geoid10","fips")

pal <- colorNumeric(palette="YlGnBu", domain=cs$homeown_rate)


popup <- paste0(cs$county,
              "<br>",
              "Homeownership= ",
              cs$homeown_rate,
              "<br",
              "homeown= ",
              prettyNum(cs$homeown_rate,big.mark=","))

map <- leaflet()%>%
  addProviderTiles("CartoDB.Positron")%>%
  addPolygons(data = cs,
              fillColor = ~pal(cs$homeown_rate),
              color = "#b2aeae",
              fillOpacity = .7,
              weight = 1,
              smoothFactor = .2,
              popup = popup)%>%
  addLegend(pal = pal,
            values = cs$homeown_rate,
            position = "bottomright",
            title = "Home Ownership",
            labFormat = labelFormat(suffix = "%"))

map

```


Once we've drawn the map, we can save it.
```{r Save the Widget}
saveWidget(widget=map,file="homeown_rate.html")
```
